### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by codeling** [SpectraCollab/ORMIR_XCT#16]
When installing as mentioned in the README via `conda env create -f environment.yml` (tried this on Windows 10 with miniconda as well as anaconda under ubuntu 22.04), I got the error:
```
ERROR: Could not find a version that satisfies the requirement itk-numerics==5.2.1 (from versions: 5.0.1, 5.1.0, 5.1.0.)
ERROR: No matching distribution found for itk-numerics==5.2.1
```

If I activate the environment (it is created despite the error) and check installed packages (pip list / conda list), I find that itk packages (itk, itk-core, itk-filtering, itk-numerics, itk-registration) are installed in version 5.3.0 already (pulled in as a simpleitk dependency maybe?). Despite the message from pip about only ITK versions 5.01, 5.1.0 and 5.1.0. being available, if I change all ITK packages from "5.2.1" to "5.3.0" in environment.yml, the environment creation proceeds without errors.

**Comment by mkuczyns** [comment]
The version of all ITK packages has been changed to 5.3.0 in the environment.yml file.
