### ISSUE TITLE
`ipl_seg` the `sigma` and `support` should be parameters, not hard-coded

### ISSUE THREAD

**Issue by njneeteson** [SpectraCollab/ORMIR_XCT#3]
In `ipl_seg` currently `sigma` is hard-coded to be `0.5`. In Danielle's guidelines for HR-pQCT standard distal site analysis, the recommended value is `sigma=0.8` for filtering before thresholding cortical and trabecular bone. I'm noticing some differences in my microarchitectural parameters and I think this discrepancy is why.

I can easily resolve this by refactoring the `ipl_seg` function to have `sigma` and `support` as optional arguments and set the default values as what you have now (`sigma=0.5`, `support=1`). However just checking if you're fine with that resolution before I go ahead.

**Comment by mkuczyns** [comment]
That sounds good to me! You can go ahead with the change.

**Comment by njneeteson** [comment]
I made `sigma` a kwarg already and I think that's sufficient for now. I'm going to close this and if anyone needs `support` to also be a kwarg in the future they can do it.
