### ISSUE TITLE
Minors in notebooks

### ISSUE THREAD

**Issue by sbonaretti** [SpectraCollab/ORMIR_XCT#4]
Hey @mkuczyns and @njneeteson , 

I am playing around with your notebooks to learn your code. Impressive work!!!

I have found some minor bugs in the notebooks, so I am writing them here. Hope it can be useful for your release!

- In all notebooks, to be able to import the package, I have to add: 
    ```
    import sys
    sys.path.append('[my_path]/ORMIR_XCT')
    ```
- Notebook *jsw_nathan.ipynb*:
  - Cell 86: `seg_image_np = sitk.GetArrayFromImage(seg_image)` missing before the visualization

- Notebook *hildebrand_notebook.ipynb*:
  - Cell 3: `compare(sphere, cylinder, link_cmap=True, axes=True, rotate=True)`, I get: `NameError: name 'compare' is not defined`. I guess `from itkwidgets import compare` is missing
  - Cell 9: `The file "../tests/data/JS_MASK.mha" does not exist`
  - Cell 12: `FileNotFoundError: [Errno 2] No such file or directory: '/Users/nathanneeteson/Documents/Data/Images/UNet/NORMXTII_0051_TL.npz'`
    
- Notebook *jsw_notebook.ipynb*:  
  - Step 4: `<img src='notebookImages/sphereFitting.png' width="250" height="250">`. Figure missing

- `compare` and `view` from `itkwidget` do not really work for me...

Best,
Serena

**Comment by njneeteson** [comment]
Hi Serena,

Your first issue would be resolved by installing the package. To set up my environment for this repo I believe I did something like:

Go to the root directory, then:
```
conda env create -f environment.yml
conda activate ormir_xct
pip install -e .
```

I think Michael will be adding more usage instructions to the README in the near future.


The other stuff, we will clean up before the first "official release." Thanks for pointing that stuff out!

**Comment by mkuczyns** [comment]
The README has been update with installation instructions and the repository has been cleaned up for the first release. I will close this issue now.
